# Generated by Django 4.1.5 on 2023-01-23 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='is_confirmed',
        ),
    ]
