# Generated by Django 4.1.5 on 2023-01-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postcode',
            field=models.PositiveIntegerField(),
        ),
    ]
