# Generated by Django 4.1.5 on 2023-01-24 08:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_address_postcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postcode',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Enter postcode in "dd-ddd" format.', regex='^\\d{2}-\\d{3}$')]),
        ),
    ]
