# Generated by Django 4.1.5 on 2023-02-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_address_postcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prepayed',
            field=models.BooleanField(default=False),
        ),
    ]
