# Generated by Django 4.1.5 on 2023-02-05 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_prepayed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='prepayed',
            new_name='payed',
        ),
    ]
