# Generated by Django 4.1.5 on 2023-02-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_description_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, upload_to='products/static/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Tee', 'Tee'), ('Hoodie', 'Hoodie'), ('Accessory', 'Accessory')], default=('Tee', 'Tee'), max_length=50),
        ),
    ]
