# Generated by Django 4.1.5 on 2023-02-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Tees', 'Tees'), ('Hoodies', 'Hoodies'), ('Accessories', 'Accessories')], default=('Tees', 'Tees'), max_length=50),
        ),
    ]
